System.register([], function(_export, _context) { return { execute: function () {
System.register("chunks:///Check.js",["./_virtual/_rollupPluginBabelHelpers.js","cc"],(function(e,t){var n,o,r,i,l,c,s,a,u,d,v,h,p,f,C,y,_,m,g,b,S,k,w,z,L,P,D,N,R;return e({_dec:void 0,_dec2:void 0,_dec3:void 0,_dec4:void 0,_class:void 0,_class2:void 0,_descriptor:void 0,_descriptor2:void 0,_descriptor3:void 0,_temp:void 0}),{setters:[function(e){n=e.applyDecoratedDescriptor,o=e.inherits,r=e.classCallCheck,i=e.possibleConstructorReturn,l=e.getPrototypeOf,c=e.initializerDefineProperty,s=e.assertThisInitialized,a=e.createClass},function(e){u=e.cclegacy,d=e._decorator,v=e.Label,h=e.Camera,p=e.ColliderComponent,f=e.Node,C=e.v3,y=e.view,_=e.Component}],execute:function(){u._RF.push({},"f282frLM9NJ37V0qmT3XW2r","Check",void 0),D=d.ccclass,N=d.property,R=[{level:"第一关",needScore:100},{level:"第二关",needScore:300},{level:"第三关",needScore:800}],e("Check",(m=D("Check"),g=N(v),b=N(v),S=N(h),m((z=n((w=function(e){function t(){var e,n;r(this,t);for(var o=arguments.length,a=new Array(o),u=0;u<o;u++)a[u]=arguments[u];return n=i(this,(e=l(t)).call.apply(e,[this].concat(a))),c(n,"score",z,s(n)),c(n,"level",L,s(n)),c(n,"camera",P,s(n)),n.count=0,n.currentLevel=R[0],n}return o(t,e),a(t,[{key:"start",value:function(){this.getComponent(p).on("onCollisionStay",this.onCollision,this)}},{key:"onCollision",value:function(e){var t=this,n=e.otherCollider.node.typeNum,o=0;"0"==n?o=1:"1"==n&&(o=3),this.playGetCount(e.otherCollider.node,o),e.otherCollider.destroy(),this.count+=o;var r=null;(r=this.count>=this.currentLevel.needScore?R.find((function(e){return t.count<=e.needScore})):this.currentLevel)||(r={level:"无限模式",needScore:99999999}),this.currentLevel=r,this.level.string=r.level,this.score.string="当前分数：".concat(this.count,"/").concat(r.needScore)}},{key:"playGetCount",value:function(e,t){var n=new f,o=n.addComponent(v);o.string="+".concat(t,"分"),n.parent=this.score.node._parent;var r=e.getPosition(),i=this.camera.worldToScreen(r);o.node.setPosition(C(i.x-y.getCanvasSize().width/2,-300,0)),this.scheduleOnce((function(){o.onDestroy()}),.5)}}]),t}(_)).prototype,"score",[g],{configurable:!0,enumerable:!0,writable:!0,initializer:function(){return null}}),L=n(w.prototype,"level",[b],{configurable:!0,enumerable:!0,writable:!0,initializer:function(){return null}}),P=n(w.prototype,"camera",[S],{configurable:!0,enumerable:!0,writable:!0,initializer:function(){return null}}),k=w))||k)),u._RF.pop()}}}));

System.register("chunks:///Games.js",["./_virtual/_rollupPluginBabelHelpers.js","cc"],(function(e,t){var i,r,n,a,o,s,c,l,u,v,p,d,f,h,y,m,C,_,g,P,b,k,z,w,D;return e({_dec:void 0,_dec2:void 0,_class:void 0,_class2:void 0,_descriptor:void 0,_temp:void 0}),{setters:[function(e){i=e.applyDecoratedDescriptor,r=e.inherits,n=e.classCallCheck,a=e.possibleConstructorReturn,o=e.getPrototypeOf,s=e.initializerDefineProperty,c=e.assertThisInitialized,l=e.createClass},function(e){u=e.cclegacy,v=e._decorator,p=e.Prefab,d=e.systemEvent,f=e.SystemEvent,h=e.view,y=e.instantiate,m=e.v3,C=e.RigidBody,_=e.Component}],execute:function(){u._RF.push({},"23e74vPHrNP/r9JxzKf4Tu7","Games",void 0),w=v.ccclass,D=v.property,e("Games",(g=w("Games"),P=D(p),g((z=i((k=function(e){function t(){var e,i;n(this,t);for(var r=arguments.length,l=new Array(r),u=0;u<r;u++)l[u]=arguments[u];return i=a(this,(e=o(t)).call.apply(e,[this].concat(l))),s(i,"circle",z,c(i)),i}return r(t,e),l(t,[{key:"onLoad",value:function(){for(var e=0;e<20;e++){var t=Math.floor(4*Math.random()-2);this.createCoin(t)}}},{key:"start",value:function(){var e=this;d.on(f.EventType.TOUCH_END,(function(t){var i=5*(t.getLocationX()/h.getCanvasSize().width)-2.5;e.createCoin(i)}))}},{key:"createCoin",value:function(e){var t=y(this.circle);this.node.addChild(t),t.setPosition(m(e,2.115,1));var i=Math.floor(10*Math.random());t.typeNum="0",i>=8&&(t.setScale(m(1,.08,1)),t.getComponent(C).mass=10,t.typeNum="1")}}]),t}(_)).prototype,"circle",[P],{configurable:!0,enumerable:!0,writable:!0,initializer:function(){return null}}),b=k))||b)),u._RF.pop()}}}));

System.register("chunks:///Startgame.js",["./_virtual/_rollupPluginBabelHelpers.js","cc"],(function(t,e){var n,r,c,a,o,s,i,u,l,p,d,f;return t({_dec:void 0,_class:void 0}),{setters:[function(t){n=t.inherits,r=t.createClass,c=t.classCallCheck,a=t.possibleConstructorReturn,o=t.getPrototypeOf},function(t){s=t.cclegacy,i=t._decorator,u=t.director,l=t.Component}],execute:function(){s._RF.push({},"478d7GN0EBJOL9D2jikx16V","Startgame",void 0),f=i.ccclass,i.property,t("Startgame",(p=f("Startgame"),p(d=function(t){function e(){return c(this,e),a(this,o(e).apply(this,arguments))}return n(e,t),r(e,[{key:"start",value:function(){}},{key:"loadMainScene",value:function(){u.loadScene("main")}}]),e}(l))||d)),s._RF.pop()}}}));

System.register("chunks:///_virtual/prerequisite-imports:main",["../Check.js","../Games.js","../Startgame.js"],(function(t,e){return{setters:[function(t){},function(t){},function(t){}],execute:function(){}}}));

(function(r) {
  r('project:///assets/scripts/Check.js', 'chunks:///Check.js');
  r('project:///assets/scripts/Games.js', 'chunks:///Games.js');
  r('project:///assets/scripts/Startgame.js', 'chunks:///Startgame.js');
  r('virtual:///prerequisite-imports:main', 'chunks:///_virtual/prerequisite-imports:main'); 
})(function(mid, cid) {
    System.register(mid, [cid], function (_export, _context) {
    var _m;
    return {
        setters: [function(m) { _m = m; }],
        execute: function () { _export(_m); }
    };
    });
});
} }; });